using System;
using AutoMapper;
using FinSenseAPI.Models;
using FinSenseAPI.DTOs.Upload;
using FinSenseAPI.DTOs.Auth;
using FinSenseAPI.DTOs.Goal;
using FinSenseAPI.Helpers;

namespace FinSenseAPI.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<Transaction, TransactionDto>()
            .ForMember(d => d.Date, o => o.MapFrom(s => s.Date.ToString("yyyy-MM-dd")));

        // Note: Token and ExpiresAt are generated by the authentication service and
        // should not be mapped automatically from User. Build AuthResponseDto in the service.

        CreateMap<Goal, GoalResponseDto>()
            .ForMember(d => d.Status, o => o.MapFrom(s => s.Status))
            .ForMember(d => d.AmountRemaining, o => o.MapFrom(s => s.TargetAmount - s.CurrentSavings))
            .ForMember(d => d.MonthsRemaining, o => o.MapFrom(s => DateHelper.GetMonthsBetween(DateTime.UtcNow, s.TargetDate)))
            .ForMember(d => d.RequiredMonthlySaving, o => o.MapFrom(s => CalculateRequiredMonthlySaving(s)))
            .ForMember(d => d.CurrentMonthlySurplus, o => o.MapFrom(s => 0m))
            .ForMember(d => d.Shortfall, o => o.MapFrom(s => CalculateRequiredMonthlySaving(s)))
            .ForMember(d => d.Reason, o => o.Ignore())
            .ForMember(d => d.Tip, o => o.Ignore());

        CreateMap<GoalRequestDto, Goal>()
            .ForMember(d => d.TargetDate, o => o.MapFrom(s => s.TargetDate))
            .ForMember(d => d.CreatedAt, o => o.MapFrom(_ => DateTime.UtcNow))
            .ForMember(d => d.Id, o => o.Ignore());

        CreateMap<RegisterRequestDto, User>()
            .ForMember(d => d.Id, o => o.MapFrom(_ => Guid.NewGuid()))
            .ForMember(d => d.CreatedAt, o => o.MapFrom(_ => DateTime.UtcNow))
            .ForMember(d => d.IsActive, o => o.MapFrom(_ => true))
            .ForMember(d => d.PasswordHash, o => o.Ignore())
            .ForMember(d => d.Email, o => o.MapFrom(s => s.Email))
            .ForMember(d => d.FullName, o => o.MapFrom(s => s.FullName));
    }

    private static decimal CalculateRequiredMonthlySaving(Goal g)
    {
        var months = DateHelper.GetMonthsBetween(DateTime.UtcNow, g.TargetDate);
        var remaining = g.TargetAmount - g.CurrentSavings;
        if (months <= 0) return Math.Round(remaining, 2);
        return Math.Round(remaining / months, 2);
    }
}
